### ISSUE TITLE
Fix assertion `win != (static_cast<MPI_Win> (static_cast<void *> (&(ompi_mpi_win_null))))'

### ISSUE THREAD

**Issue by janciesko** [kokkos/kokkos-remote-spaces#30]
TEST_CATEGORY.test_subview failing with 

```
#0  0x000020000060fcb0 in __GI_raise (sig=<optimized out>)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x000020000061200c in __GI_abort () at abort.c:90
#2  0x00002000006057d4 in __assert_fail_base (
    fmt=0x20000076b6d0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x1014fcd8 "win != (static_cast<MPI_Win> (static_cast<void *> (&(ompi_mpi_win_null))))",
---Type <return> to continue, or q <return> to quit---
    file=0x10150218 "/g/g92/ciesko1/Kokkos/kokkos-remote-spaces-reduction-example/src/MPISPACE/Kokkos_MPISpace_DataHandle.hpp", line=<optimized out>,
    function=<optimized out>) at assert.c:92
#3  0x00002000006058c4 in __GI___assert_fail (
    assertion=0x1014fcd8 "win != (static_cast<MPI_Win> (static_cast<void *> (&(ompi_mpi_win_null))))",
    file=0x10150218 "/g/g92/ciesko1/Kokkos/kokkos-remote-spaces-reduction-example/src/MPISPACE/Kokkos_MPISpace_DataHandle.hpp", line=<optimized out>,
    function=0x10150390 <Kokkos::Impl::MPIDataElement<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >, void> Kokkos::Impl::MPIDataHandle<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> > >::operator()<int>(int const&, int const&) const::__PRETTY_FUNCTION__> "Kokkos::Impl::MPIDataElement<T, Traits> Kokkos::Impl::MPIDataHandle<T, Traits>::operator()(const int&, const iType&) const [with iType = int; T = int; Traits = Kokkos::ViewTraits<int*, Kokkos::Partiti"...) at assert.c:101
#4  0x00000000100933ec in Kokkos::Impl::MPIDataElement<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >, void> Kokkos::Impl::MPIDataHandle<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> > >::operator()<int>(int const&, int const&) const ()
#5  0x000000001008fae8 in Kokkos::Impl::MPIDataElement<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::Me---Type <return> to continue, or q <return> to quit---
moryTraits<1u> >, void> const Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >, Kokkos::Experimental::RemoteSpaceSpecializeTag>::reference<int, Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> > >(int const&, std::enable_if<((std::is_same<Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >::array_layout, Kokkos::PartitionedLayoutLeft>::value||std::is_same<Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >::array_layout, Kokkos::PartitionedLayoutRight>::value)||std::is_same<Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >::array_layout, Kokkos::PartitionedLayoutStride>::value)&&Kokkos::RemoteSpaces_MemoryTraits<Kokkos::ViewTraits<int*, Kokkos::PartitionedLayoutStride, Kokkos::Experimental::MPISpace, Kokkos::MemoryTraits<1u> >::memory_traits>::dim0_is_pe, void>::type*) const ()
#6  0x0000000010084988 in void test_subview1D<int>(int, int, int, int)::{lambda(int)#1}::operator()(int) const ()
#7  0x0000000010098cd0 in std::enable_if<std::is_same<void, void>::value, void>::type Kokkos::Impl::ParallelFor<void test_subview1D<int>(int, int, int, int)::{lambda(int)#1}, Kokkos::RangePolicy<Kokkos::Serial>, Kokkos::RangePolicy>::exec<void>() const ()
#8  0x000000001009391c in Kokkos::Impl::ParallelFor<void test_subview1D<int>(int, int, int, int)::{lambda(int)#1}, Kokkos::RangePolicy<Kokkos::Serial>, Kokkos::---Type <return> to continue, or q <return> to quit---
RangePolicy>::execute() const ()
```

Needs updating how we deallocate windows with a shared space instance.

**Comment by janciesko** [comment]
Resolved
